services:
  mysql:
    image: mysql:9.3.0
    container_name: mysql-db
    env_file:
      - ../.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: backend-api
    env_file:
      - ../.env
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    restart: always

volumes:
  mysql_data:
